### PR TITLE
adds missing install instructions (fixes #1)

### LINKED ISSUE #1: map_store is missing install rules
Hence, there are no executables in the deb.

### PR DESCRIPTION
**Pull request by bit-pirate**
This should fix the install problem and also removes the absolute namespace for the `map` topic.

### CODE REVIEW

**Comment by bit-pirate** [comment]
Anyone out there how could merge this and re-release the package? Or alternatively give me access to this and the release repo and I'll do it.

We need this for TurtleBot. That's why I'm being a bit impatient here.

**Comment by stonier** [comment]
_bump_

**Comment by hershwg** [comment]
sorry, was on vacation.  Thanks for the contribution!

**Comment by bit-pirate** [comment]
No problem! Could you please trigger a re-release as well? Thanks a lot!

**Comment by hershwg** [comment]
release triggered.

**Pull request merged**
